### PR TITLE
Add UmlautAdaptarr

### PR DESCRIPTION
**Pull request by PCJones**
LMK if you have any questions :)
https://github.com/PCJones/UmlautAdaptarr

### CODE REVIEW

**Comment by Ravencentric** [comment]
Can you explain what it actually does? What problems is it solving (maybe some links to open issues)? Unfortunately I do not speak German.

**Comment by IC3P3** [comment]
UnlautAdaptarr is there because German has it's special characters like ä, ö, ü . The *arrs have problems with it, so UmlautAdaptarr acts as an adapter between the indexer and Sonarr/Radarr to replace these special characters with a simple a, o, u. 

Also some groups are known for bad naming and while Sonarr/Radarr search for English titles like "GERMAN" they have "DEUTSCH" in their titles which also gets replace with "GERMAN".

So it's just a tool to compensate for bad regional naming to prevent Sonarr/Radarr ignoring the correct titles.

**Comment by PCJones** [comment]
I'm limited on time atm but I will provide more information asap

**Comment by Ravencentric** [comment]
Sounds like a cool project to me, thanks!

**Pull request merged**
